definitions:
  dto.DeleteOrderByIDResponse:
    properties:
      message:
        example: Order with id 69 has been successfully deleted
        type: string
      statusCode:
        example: 200
        type: integer
    type: object
  dto.GetAllOrdersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.OrderData'
        type: array
      message:
        example: success
        type: string
      statusCode:
        example: 200
        type: integer
    type: object
  dto.GetOrderByIDResponse:
    properties:
      data:
        $ref: '#/definitions/dto.OrderData'
      message:
        example: success
        type: string
      statusCode:
        example: 200
        type: integer
    type: object
  dto.ItemData:
    properties:
      createdAt:
        example: "2023-03-19T18:55:00+07:00"
        type: string
      description:
        example: Ini adalah sebuah barang yang dipesan
        type: string
      id:
        example: 2
        type: integer
      itemCode:
        example: BRNG-001
        type: string
      orderId:
        example: 1
        type: integer
      quantity:
        example: 1
        type: integer
      updatedAt:
        example: "2023-03-19T18:55:00+07:00"
        type: string
    type: object
  dto.NewItemRequest:
    properties:
      description:
        example: Ini adalah sebuah barang yang dipesan
        type: string
      itemCode:
        example: BRNG-001
        type: string
      quantity:
        example: 1
        type: integer
    required:
    - description
    - itemCode
    - quantity
    type: object
  dto.NewOrderRequest:
    properties:
      customerName:
        example: Taufik Hidayat
        type: string
      items:
        items:
          $ref: '#/definitions/dto.NewItemRequest'
        type: array
      orderedAt:
        example: "2023-03-19T18:55:00+07:00"
        type: string
    required:
    - customerName
    - items
    type: object
  dto.NewOrderResponse:
    properties:
      data:
        $ref: '#/definitions/dto.NewOrderRequest'
      message:
        example: Order with id 69 has been successfully created
        type: string
      statusCode:
        example: 201
        type: integer
    type: object
  dto.OrderData:
    properties:
      createdAt:
        example: "2023-03-19T18:55:00+07:00"
        type: string
      customerName:
        example: Taufik Hidayat
        type: string
      id:
        example: 1
        type: integer
      items:
        items:
          $ref: '#/definitions/dto.ItemData'
        type: array
      updatedAt:
        example: "2023-03-19T18:55:00+07:00"
        type: string
    type: object
  errs.MessageErrData:
    properties:
      error:
        example: BAD_REQUEST
        type: string
      message:
        example: This is an error message
        type: string
      statusCode:
        example: 400
        type: integer
    type: object
info:
  contact: {}
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAllOrdersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.MessageErrData'
      summary: List orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Create an order by json
      parameters:
      - description: Create order request body
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/dto.NewOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.NewOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.MessageErrData'
      summary: Create order
      tags:
      - orders
  /orders/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an order by id
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeleteOrderByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errs.MessageErrData'
      summary: Delete order
      tags:
      - orders
    get:
      consumes:
      - application/json
      description: Get an order by id
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetOrderByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.MessageErrData'
      summary: Find order
      tags:
      - orders
    patch:
      consumes:
      - application/json
      description: Update an order by json
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update order request body
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/dto.NewOrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetOrderByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errs.MessageErrData'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.MessageErrData'
      summary: Update order
      tags:
      - orders
swagger: "2.0"